from htrc.torchlite.widgets.mapping_contributor_data import MappingContributorDataWidget
from htrc.torchlite.widgets.publication_date_timeline import PublicationDateTimelineWidget
from htrc.torchlite.widgets.simple_tag_cloud import SimpleTagCloudWidget
from htrc.torchlite.widgets.summary import SummaryWidget

ALL_WIDGETS = MappingContributorDataWidget | PublicationDateTimelineWidget | SimpleTagCloudWidget | SummaryWidget
