[tool.poetry]
name = "torchlite"
version = "0.1.0"
description = ""
authors = ["cwulfman <cwulfman@princeton.edu>"]
readme = "README.org"
packages = [
  {include = "htrc/torchlite", from = "src"},
  {include = "htrc/ef/datamodels", from = "src"},
]

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.28.2"
pydantic = "^1.10.6"
fastapi = "^0.95.0"
nltk = "^3.8.1"


[tool.poetry.group.dev.dependencies]
pyright = "^1.1.299"
pytest = "^7.2.2"
black = "^23.1.0"
flake8 = "^6.0.0"
isort = "^5.12.0"
uvicorn = "^0.21.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
