[tool.poetry]
name = "backend"
version = "0.1.0"
description = ""
authors = ["cwulfman <cwulfman@princeton.edu>"]
readme = "README.md"
packages = [{include = "backend", from = "src"}]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.90.1"
requests = "^2.28.2"
htrc-ef-lib = { git = "git@github.com:htrc/HTRC-EF-Lib.git" }
nltk = "^3.8.1"

[tool.poetry.group.dev.dependencies]
pyright = "^1.1.293"
uvicorn = "^0.20.0"
pytest = "^7.2.1"
black = "^23.1.0"
flake8 = "^6.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
