#+title: Torchlite Backend

* The develop branch
The *develop* branch of this repository contains the code now running on
HTRC's servers.  Instructions for installing and running it can be
found at the bottom of this document.

Boris Capitanu is well familiar with how to start the service; he wrote the deployment code, and he helped
develop the startup script in htrc/torchlite/app.py.

The API documentation derives from the code and is generated by
FastAPI; see <https://fastapi.tiangolo.com/features/>. Start the
server and go to the /docs endpoint.


There are two modules:

- ef (Extracted Features) ::  A Python object-oriented interface to
  <https://tools.htrc.illinois.edu/ef-api>.  The backend uses it to
  get data from the EF database; it is also designed to be installed
  separately and used in, for example, Jupyter notebooks.  An earlier
  version of this module can be found in this repository
  (https://github.com/htrc/HTRC-EF-Lib); someone may wish to update
  that repository and serve the code from there.

- torchlite :: the back-end code
  - app.py :: the "main module" called by the uvicorn webserver to run
    the application

  - logutils.py and middleware.py :: runtime monitoring code, written
    by Boris.

  - dashboards.py :: Implements a Dashboard class

  - worksets.py :: implements a Workset class

  - widgets :: a module that implements widgets, following the
    architecture I have documented.  There is one implemented
    projector, the TimelineProjector, used by the TimeLineWidget

  - filters.py :: implements a number of Filter objects.  These were
    never deployed

* The purge branch
The *purge* branch contains the latest iteration on the codebase that
provides a stateless, asynchronous back end. It is a major rewrite and
restructuring, and it contains many new features and enhancements,
including an updated EFApi class and a Token class for doing work with
actual Extracted Features. Versions of this codebase have been
available since February.



* Prerequisites
 - Python 3.11+
 - Poetry 1.4.2+
 - git
* Installation
#+begin_src shell
  git clone git@github.com:htrc/torchlite-backend.git
  # for getting the "latest stable" version, uncomment and run the next line
  # git checkout main 
  cd torchlite-backend
  poetry install --sync
#+end_src
* Running the Backend in Development
#+begin_src shell
  poetry run uvicorn htrc.torchlite.app:api --reload
#+end_src
  
* A Quick Demonstration
Point your browser at <http://localhost:8000/docs,> and play with the endpoints. Use the demo dashboard and the TimeLineWidget to get a quick result:

#+begin_src shell
  curl http://127.0.0.1:8000/dashboards/demo/widget/TimeLineWidget/data
#+end_src
