from _typeshed import Incomplete
from htrc.torchlite.widgets.projectors import Projector as Projector

class Widget:
    id: Incomplete
    projector: Incomplete
    def __init__(self) -> None: ...
    def reset(self) -> None: ...
    def get_data(self, workset): ...

class TimeLineWidget(Widget):
    projector: Incomplete
    def __init__(self) -> None: ...
