* Torchlite Backend Demonstration
The most important part of Torchlite is its /dashboard:/ a React application that runs in a browser and enables users to select worksets, clean and filter workset data, and see data visualizations.  Torchlite's dashboard also gives users the ability to save data so that it may be displayed and explored in a Jupyter Notebook.

Behind the scenes, Torchlite has a server application that performs vital functions for the dashboard: interacting with HTRC's Extracted Features database and performing sometimes elaborate computations that might lag if performed in the browser.  This /three-tiered architecture/ -- a presentation layer, a data layer, and a business layer -- is very common on the web.  It is favored by web developers because separating these concerns make applications faster to develop, more flexible to deploy, and easier to maintain.

This demonstration shows Torchlite's back-end application in action.  The application is in active development, and not all of its functions have been implemented yet; it may also be slow and buggy.  And of course, this demonstration does not include the graphical dashboard!  But it does show how the graphical dashboard communicates with the backend to get data and execute user requests.

We're going to show you how to install the Torchlite backend application on your own computer, start it up, and use your web browser to interact with it.

** Getting Ready
To install and run this demonstration, you need to have a computer that is connected to the Internet, and you must have permission to install software on it.  For now, we are going to assume you are running a recent version of MacOS on a Macintosh computer; if you have a Windows machine or a Linux machine, please contact us for help.

If you have never installed software on your computer, you may want to get some help in installing the basic tools and using the command line.

*** Install Homebrew
#+begin_src shell
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
#+end_src
*** Install asdf
#+begin_src shell
  brew install asdf
#+end_src

*** Install a Recent Version of Python
There are many tutorials and recipes on the Web showing how to install Python 3 on a Mac; if you have never installed software on your computer, you may want to get some help, as you are going to be using the command line to

#+begin_src shell
  asdf plugin-add python
  asdf install python 3.11.0
#+end_src
*** Install Poetry
#+begin_src shell
  curl -sSL https://install.python-poetry.org | python3 -
#+end_src

*** Clone the Torchlite Backend GitHub Repository
#+begin_src shell
  git clone git@github.com:htrc/torchlite-backend.git
#+end_src
*** Install the Torchlite Backend Application
#+begin_src shell
  cd torchlite-backend
  asdf local python 3.11.0
  poetry install
#+end_src
*** Start the Torchlite Backend Application
#+begin_src shell
  cd src
  poetry run uvicorn app:api
#+end_src

*** Interact with the Server
Now you can interact with the server.  One way is to use the OpenAPI endpoint at [[http://127.0.0.1:8000/docs][http://127.0.0.1:8000/docs]]: you can use form fields, links, and buttons to make requests and see responses.

Another way is to use a commandline tool like curl.  Here's how you would add a timeline widget to the default dashboard:

#+begin_src shell
  curl -X 'POST' \
    'http://127.0.0.1:8000/dashboards/default/widgets/TimeLineWidget' \
    -H 'accept: application/json' \
    -d ''
#+end_src

Now you can ask the new widget for data (your widget id will be different):
#+begin_src shell
  curl -X 'GET' \
    'http://127.0.0.1:8000/dashboards/default/widget/c9d0f15c-d548-11ed-bc15-acde48001122/data' \
    -H 'accept: application/json'
#+end_src

#+begin_src json
  [
    {
      "htid": "mdp.35112103187797",
      "pubDate": 1947
    },
    {
      "htid": "mdp.39015058744122",
      "pubDate": 2001
    },
    {
      "htid": "uc1.$b684263",
      "pubDate": 1889
    },
    {
      "htid": "uc1.32106011187561",
      "pubDate": 2001
    }
  ]
#+end_src
