from _typeshed import Incomplete
from htrc.torchlite.worksets import Workset as Workset

class Projector:
    projection: Incomplete
    def __init__(self) -> None: ...
    def project(self, workset: Workset): ...

class TimeLineProjector(Projector):
    def __init__(self) -> None: ...
    projection: Incomplete
    def project(self, workset: Workset): ...
