"""adds dashboards table

Revision ID: bb492cdb70ac
Revises: 
Create Date: 2023-10-03 18:28:25.088299

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_nested_mutable
from htrc.torchlite.models.schemas import FilterSettings
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bb492cdb70ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('workset_id', sa.String(), nullable=False),
    sa.Column('filters', sqlalchemy_nested_mutable.mutable.PydanticType(FilterSettings), nullable=True),
    sa.Column('widgets', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboards_created_at'), 'dashboards', ['created_at'], unique=False)
    op.create_index(op.f('ix_dashboards_owner_id'), 'dashboards', ['owner_id'], unique=False)
    op.create_index(op.f('ix_dashboards_updated_at'), 'dashboards', ['updated_at'], unique=False)
    op.create_index(op.f('ix_dashboards_workset_id'), 'dashboards', ['workset_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dashboards_workset_id'), table_name='dashboards')
    op.drop_index(op.f('ix_dashboards_updated_at'), table_name='dashboards')
    op.drop_index(op.f('ix_dashboards_owner_id'), table_name='dashboards')
    op.drop_index(op.f('ix_dashboards_created_at'), table_name='dashboards')
    op.drop_table('dashboards')
    # ### end Alembic commands ###
