import htrc.ef.datamodels as ef
from typing import List, Optional, Union

def cleanId(id: str) -> str: ...

class Api:
    base_uri: str
    worksets_uri: str
    volumes_uri: str
    def get(self, uri: str) -> dict: ...
    def get_workset(self, wsid: str) -> ef.Workset: ...
    def get_workset_metadata(self, wsid: str, fields: Optional[List[str]]) -> List[ef.Volume]: ...
    def get_workset_volumes(self, wsid: str, fields: Optional[List[str]]) -> List[ef.Volume]: ...
    def get_volume_data(self, htid: str, pos: Union[bool, None] = ..., fields: Optional[List[str]] = ...) -> List[ef.Volume]: ...
    def get_volume_metadata(self, htid: str, fields: Optional[List[str]]) -> List[ef.Volume]: ...
    def get_pages(self, htid: str, seq: Optional[List[str]], pos: Optional[bool] = ..., fields: Optional[List[str]] = ...) -> List[ef.Volume]: ...
