from _typeshed import Incomplete
from torchlite.filters import torchlite_lemmatizer as torchlite_lemmatizer, torchlite_stemmer as torchlite_stemmer, torchlite_stopword_filter as torchlite_stopword_filter

def setup_demo(app, ef_api) -> None: ...

origins: Incomplete
api: Incomplete
ef_api: Incomplete
app: Incomplete

async def read_root(): ...
async def get_worksets(): ...
async def get_workset(workset_id): ...
async def get_dashboards(): ...
async def create_dashboard(): ...
async def get_dashboard(dashboard_id): ...
async def put_dashboard_workset(dashboard_id: str, workset_id: str): ...
async def post_dashboard_widget(dashboard_id: str, widget_type: str): ...
async def get_widget_data(dashboard_id: str, widget_id: str): ...
