from _typeshed import Incomplete
from htrc.torchlite.widgets import Widget as Widget
from htrc.torchlite.worksets import Workset as Workset
from pydantic import UUID1 as UUID1
from typing import Union

class Dashboard:
    id: Incomplete
    widgets: Incomplete
    token_data: Incomplete
    token_filters: Incomplete
    def __init__(self) -> None: ...
    @property
    def info(self): ...
    def reset_token_data(self) -> None: ...
    def reset_data(self) -> None: ...
    @property
    def workset(self) -> Union[Workset, None]: ...
    @workset.setter
    def workset(self, workset: Workset): ...
    def add_widget(self, widget: Widget): ...
    def get_widget(self, widget_id: UUID1): ...
    def delete_widget(self, widget_id: UUID1): ...
