from _typeshed import Incomplete
from collections import Counter

def torchlite_stemmer(token_list: Counter): ...
def torchlite_lemmatizer(token_list: Counter): ...
def torchlite_stopword_filter(token_list: Counter): ...

class Filter:
    id: Incomplete
    type: str
    filter_fns: Incomplete
    def __init__(self, *fns) -> None: ...
    def compose(self, f, g): ...
    def apply(self, token_list): ...

class FilterFactory:
    registry: Incomplete
    def __init__(self) -> None: ...
    def register(self, key, fn) -> None: ...
    def make_filter(self, fnames): ...
